org: ${file(./config.yml):aws.org, 'default-org'}
# "service" är namnet på detta projekt
service: fishScore

plugins:
  - serverless-wsgi
  - serverless-prune-plugin
  - serverless-python-requirements

# Anslutning till Flask
custom:
  wsgi:
    app: app.app
  prune:
    automatic: true
    number: 5  # spara endast 5 senaste versioner


provider:
  name: aws
  runtime: python3.12
  stage: api    
  region: eu-north-1 
  iam:
    role: ${file(./config.yml):aws.role}
  environment:
    USERS_TABLE: fishScore
    WEBSOCKET_ENDPOINT:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: WebsocketsApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - ${self:provider.stage}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  WebsocketHandler:
    handler: websocket/handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

  ScoreStreamProcessor:
    handler: streams/score_stream.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [UsersTable, StreamArn]
          startingPosition: LATEST
          batchSize: 10
resources:
  Resources:
    WebsocketsApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: fishscore-websocket-api
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.action"

    UsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain   # Använd samma tabell vid deploy
      Properties:
        TableName: fishScore
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: lookupType
            AttributeType: S
          - AttributeName: lookupValue
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: LookupIndex
            KeySchema:
              - AttributeName: lookupType
                KeyType: HASH
              - AttributeName: lookupValue
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
