# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./config.yml):aws.org, 'default-org'}
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fishScore

plugins:
  - serverless-wsgi
  - serverless-prune-plugin
  - serverless-python-requirements

# Connection to Flask
custom:
  wsgi:
    app: app.app
  prune:
    automatic: true
    number: 5  # keep the 5 latest versions


provider:
  name: aws
  runtime: python3.12
  stage: api    # Stage blir /api
  region: eu-north-1 
  iam:
    role: ${file(./config.yml):aws.role}
  environment:
    USERS_TABLE: fishScore

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  # createUser:
  #   handler: functions/auth/PostRegisterUser/handler.handler
  #   events:
  #     - http:
  #         path: /auth/register
  #         method: POST

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain   # Keep the same table when deploying
      Properties:
        TableName: fishScore
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: lookupPK
            AttributeType: S
          - AttributeName: lookupSK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: lookupPK
                KeyType: HASH
              - AttributeName: lookupSK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
